name: myproject
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - torchaudio==2.5.1+cu121
      - transformers==4.47.1
      - accelerate==1.2.1
      - datasets==3.6.0
      - peft==0.15.2
      - evaluate==0.4.3
      - safetensors==0.5.3
      - sentencepiece==0.2.0
      - numpy==1.26.3
      - tqdm==4.67.1
      - vllm==0.6.6.post1
